/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consistencyindex;

/**
 *
 * @author thedadams
 */
public class Consistency extends javax.swing.JFrame {

    private ConsistencyIndexObject player1;

    /**
     * Creates new form NewJFrame
     */
    public Consistency() {
        initComponents();
        player1 = new ConsistencyIndexObject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        maxHitStreakPlayer2 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        obpPlayer2 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        medianNoBaseStreakPlayer1 = new javax.swing.JLabel();
        medianNoBaseStreakPlayer2 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        penOnBaseStreakPlayer2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lastNamePlayer1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        maxNoBaseStreakPlayer1 = new javax.swing.JLabel();
        onBaseConsistencyPlayer1 = new javax.swing.JLabel();
        maxOnBaseStreakPlayer2 = new javax.swing.JLabel();
        penHitStreakPlayer2 = new javax.swing.JLabel();
        penHitStreakPlayer1 = new javax.swing.JLabel();
        maxHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        yearStartPlayer2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maxNoBaseStreakPlayer2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        averageNoHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        averageHitStreakPlayer2 = new javax.swing.JLabel();
        averageNoHitStreakPlayer2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        obpPlayer1 = new javax.swing.JLabel();
        medianNoHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        penNoBaseStreakPlayer2 = new javax.swing.JLabel();
        firstNamePlayer1 = new javax.swing.JTextField();
        penNoHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        averageNoBaseStreakPlayer2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        onBaseConsistencyPlayer2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        maxOnBaseStreakPlayer1 = new javax.swing.JLabel();
        averageOnBaseStreakPlayer2 = new javax.swing.JLabel();
        medianOnBaseStreakPlayer1 = new javax.swing.JLabel();
        lastNamePlayer2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        firstNamePlayer2 = new javax.swing.JTextField();
        penNoBaseStreakPlayer1 = new javax.swing.JLabel();
        penOnBaseStreakPlayer1 = new javax.swing.JLabel();
        medianHitStreakPlayer2 = new javax.swing.JLabel();
        averageHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        penNoHitStreakPlayer2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hitConsistencyPlayer1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        medianNoHitStreakPlayer2 = new javax.swing.JLabel();
        baPlayer2 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        averageOnBaseStreakPlayer1 = new javax.swing.JLabel();
        averageNoBaseStreakPlayer1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hitConsistencyPlayer2 = new javax.swing.JLabel();
        medianOnBaseStreakPlayer2 = new javax.swing.JLabel();
        baPlayer1 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        yearStartPlayer1 = new javax.swing.JTextField();
        medianHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        maxNoHitStreakPlayer2 = new javax.swing.JLabel();
        maxNoHitStreakPlayer1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        errorReport1 = new javax.swing.JLabel();
        errorReport2 = new javax.swing.JLabel();
        yearEndPlayer1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        yearEndPlayer2 = new javax.swing.JTextField();
        go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maxHitStreakPlayer2.setText(" ");

        jLabel52.setText("Max Hit Streak: ");

        jLabel34.setText("First Long Streak Counted:");

        obpPlayer2.setText(" ");

        jLabel46.setText("Hit Consistency Index: ");

        medianNoBaseStreakPlayer1.setText(" ");

        medianNoBaseStreakPlayer2.setText(" ");

        jLabel39.setText("Median Hit Streak: ");

        jLabel3.setText("Max No Base Streak: ");

        penOnBaseStreakPlayer2.setText(" ");

        jLabel50.setText("Median Hit Streak: ");

        jLabel38.setText("Median No Hit Streak: ");

        jLabel19.setText("Median On Base Streak: ");

        jLabel51.setText("Median No Hit Streak: ");

        jLabel18.setText("Median No Base Streak: ");

        lastNamePlayer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNamePlayer1FocusGained(evt);
            }
        });

        jLabel26.setText("On Base Consistency Index: ");

        maxNoBaseStreakPlayer1.setText(" ");

        onBaseConsistencyPlayer1.setText(" ");

        maxOnBaseStreakPlayer2.setText(" ");

        penHitStreakPlayer2.setText(" ");

        penHitStreakPlayer1.setText(" ");

        maxHitStreakPlayer1.setText(" ");

        jLabel23.setText("Yr Start: ");

        yearStartPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearStartPlayer2ActionPerformed(evt);
            }
        });
        yearStartPlayer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearStartPlayer2FocusGained(evt);
            }
        });

        jLabel27.setText("First Top Streak Counted:");

        jLabel5.setText("First Long Streak Counted:");

        maxNoBaseStreakPlayer2.setText(" ");

        jLabel28.setText("Batting Average: ");

        jLabel30.setText("On Base Percentage: ");

        averageNoHitStreakPlayer1.setText(" ");

        jLabel47.setText("Hit Consistency Index: ");

        jLabel53.setText("First Long Streak Counted:");

        averageHitStreakPlayer2.setText(" ");

        averageNoHitStreakPlayer2.setText(" ");

        jLabel9.setText("Max On Base Streak: ");

        jLabel21.setText("Average On Base Streak: ");

        obpPlayer1.setText(" ");

        medianNoHitStreakPlayer1.setText(" ");

        jLabel20.setText("Average No Base Streak: ");

        jLabel15.setText("On Base Percentage: ");

        jLabel36.setText("Max No Base Streak: ");

        penNoBaseStreakPlayer2.setText(" ");

        firstNamePlayer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNamePlayer1FocusGained(evt);
            }
        });

        penNoHitStreakPlayer1.setText(" ");

        jLabel33.setText("Max No Hit Streak: ");

        jLabel32.setText("First Long Streak Counted:");

        averageNoBaseStreakPlayer2.setText(" ");

        jLabel29.setText("First Long Streak Counted:");

        jLabel13.setText("On Base Consistency Index: ");

        onBaseConsistencyPlayer2.setText(" ");

        jLabel40.setText("Average No Hit Streak: ");

        maxOnBaseStreakPlayer1.setText(" ");

        averageOnBaseStreakPlayer2.setText(" ");

        medianOnBaseStreakPlayer1.setText(" ");

        lastNamePlayer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNamePlayer2FocusGained(evt);
            }
        });

        jLabel6.setText("Median On Base Streak: ");

        firstNamePlayer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNamePlayer2FocusGained(evt);
            }
        });

        penNoBaseStreakPlayer1.setText(" ");

        penOnBaseStreakPlayer1.setText(" ");

        medianHitStreakPlayer2.setText(" ");

        averageHitStreakPlayer1.setText(" ");

        jLabel16.setText("Last Name: ");

        penNoHitStreakPlayer2.setText(" ");

        jLabel37.setText("Max No Hit Streak: ");

        jLabel14.setText("Batting Average: ");

        jLabel17.setText("Last Name: ");

        hitConsistencyPlayer1.setText(" ");

        jLabel8.setText("Average On Base Streak: ");

        jLabel31.setText("Max Hit Streak: ");

        medianNoHitStreakPlayer2.setText(" ");

        baPlayer2.setText(" ");

        jLabel48.setText("Average Hit Streak: ");

        jLabel7.setText("Median No Base Streak: ");

        averageOnBaseStreakPlayer1.setText(" ");

        averageNoBaseStreakPlayer1.setText(" ");

        jLabel4.setText("First Long Streak Counted:");

        jLabel1.setText("First Name:");

        hitConsistencyPlayer2.setText(" ");

        medianOnBaseStreakPlayer2.setText(" ");

        baPlayer1.setText(" ");

        jLabel41.setText("Average Hit Streak: ");

        jLabel22.setText("First Name:");

        yearStartPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearStartPlayer1ActionPerformed(evt);
            }
        });
        yearStartPlayer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearStartPlayer1FocusGained(evt);
            }
        });

        medianHitStreakPlayer1.setText(" ");

        jLabel35.setText("Max On Base Streak: ");

        jLabel10.setText("Average No Base Streak: ");

        maxNoHitStreakPlayer2.setText(" ");

        maxNoHitStreakPlayer1.setText(" ");

        jLabel2.setText("Yr Start:");

        jLabel54.setText("First Long Streak Counted:");

        jLabel49.setText("Average No Hit Streak: ");

        errorReport1.setText("For entire career, enter \"Yr Start\" as 0.");

        errorReport2.setText("To calculate up to latest year, leave Yr End blank.");

        yearEndPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearEndPlayer1ActionPerformed(evt);
            }
        });
        yearEndPlayer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearEndPlayer1FocusGained(evt);
            }
        });

        jLabel11.setText("Yr End:");

        jLabel24.setText("Yr End: ");

        yearEndPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearEndPlayer2ActionPerformed(evt);
            }
        });
        yearEndPlayer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearEndPlayer2FocusGained(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel38)
                                .add(jLabel40)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(191, 191, 191)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(medianNoHitStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(averageNoHitStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel7)
                                        .add(jLabel10))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(medianNoBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(averageNoBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(maxNoHitStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(penNoHitStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(jLabel33)
                                .add(jLabel29)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel3)
                                        .add(jLabel5))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(penNoBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(maxNoBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(firstNamePlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel16)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lastNamePlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(87, 87, 87)
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(yearStartPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel11)
                        .add(18, 18, 18)
                        .add(yearEndPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel22)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(firstNamePlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lastNamePlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(231, 231, 231))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jPanel1Layout.createSequentialGroup()
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel46, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel15)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel14))
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jPanel1Layout.createSequentialGroup()
                                                    .add(30, 30, 30)
                                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(onBaseConsistencyPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(obpPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(baPlayer1)))
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .add(29, 29, 29)
                                                    .add(hitConsistencyPlayer1)))
                                            .add(357, 357, 357))
                                        .add(errorReport1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jPanel1Layout.createSequentialGroup()
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(jLabel32)
                                                            .add(jLabel35))
                                                        .add(28, 28, 28)
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(penOnBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                            .add(maxOnBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                    .add(jPanel1Layout.createSequentialGroup()
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                            .add(jLabel47, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel54)
                                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel28)
                                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel30)
                                                            .add(jLabel26, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(jPanel1Layout.createSequentialGroup()
                                                                .add(28, 28, 28)
                                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                    .add(baPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                    .add(onBaseConsistencyPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                    .add(obpPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, maxHitStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, penHitStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .add(29, 29, 29)
                                                                .add(hitConsistencyPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                                .add(41, 41, 41)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel37)
                                                    .add(jLabel53)
                                                    .add(jPanel1Layout.createSequentialGroup()
                                                        .add(1, 1, 1)
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(jLabel36)
                                                            .add(jLabel34))))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(averageNoHitStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(maxNoBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(maxNoHitStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(penNoHitStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(medianNoHitStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(penNoBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(565, 565, 565)
                                                .add(jLabel23)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(yearStartPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(369, 369, 369)
                                                .add(errorReport2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel39)
                                                    .add(jLabel41))
                                                .add(30, 30, 30)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(medianHitStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, averageHitStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel6)
                                                    .add(jLabel8))
                                                .add(28, 28, 28)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(medianOnBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, averageOnBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel27)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel31))
                                                .add(30, 30, 30)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, maxHitStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, penHitStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel4)
                                                    .add(jLabel9))
                                                .add(28, 28, 28)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(maxOnBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(penOnBaseStreakPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel19)
                                                    .add(jLabel21))
                                                .add(28, 28, 28)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(medianOnBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, averageOnBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(43, 43, 43)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel18)
                                                    .add(jLabel20))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(medianNoBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(averageNoBaseStreakPlayer2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel50)
                                                    .add(jLabel48))
                                                .add(28, 28, 28)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(medianHitStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, averageHitStreakPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(41, 41, 41)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel51)
                                                    .add(jLabel49))))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .add(jLabel24)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(yearEndPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {averageNoBaseStreakPlayer1, averageNoHitStreakPlayer1, maxNoBaseStreakPlayer1, maxNoHitStreakPlayer1, medianNoBaseStreakPlayer1, medianNoHitStreakPlayer1, penNoBaseStreakPlayer1, penNoHitStreakPlayer1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageHitStreakPlayer1, averageOnBaseStreakPlayer1, baPlayer1, hitConsistencyPlayer1, maxHitStreakPlayer1, maxOnBaseStreakPlayer1, medianHitStreakPlayer1, medianOnBaseStreakPlayer1, obpPlayer1, onBaseConsistencyPlayer1, penHitStreakPlayer1, penOnBaseStreakPlayer1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageHitStreakPlayer2, averageOnBaseStreakPlayer2, baPlayer2, hitConsistencyPlayer2, maxHitStreakPlayer2, medianHitStreakPlayer2, medianOnBaseStreakPlayer2, obpPlayer2, onBaseConsistencyPlayer2, penHitStreakPlayer2, penOnBaseStreakPlayer2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel19, jLabel21, jLabel26, jLabel28, jLabel30, jLabel32, jLabel35, jLabel47, jLabel48, jLabel50, jLabel52, jLabel54}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel18, jLabel20, jLabel34, jLabel36, jLabel37, jLabel49, jLabel51, jLabel53, lastNamePlayer2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel27, jLabel31, jLabel39, jLabel4, jLabel41, jLabel46, jLabel6, jLabel8, jLabel9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel10, jLabel29, jLabel3, jLabel33, jLabel38, jLabel40, jLabel5, jLabel7, lastNamePlayer1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageNoBaseStreakPlayer2, averageNoHitStreakPlayer2, maxNoBaseStreakPlayer2, maxNoHitStreakPlayer2, medianNoBaseStreakPlayer2, medianNoHitStreakPlayer2, penNoBaseStreakPlayer2, penNoHitStreakPlayer2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(yearStartPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(lastNamePlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(firstNamePlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(yearEndPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(maxNoBaseStreakPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(penNoBaseStreakPlayer1)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(maxOnBaseStreakPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(penOnBaseStreakPlayer1))))
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(medianNoBaseStreakPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(averageNoBaseStreakPlayer1)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(medianOnBaseStreakPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(averageOnBaseStreakPlayer1))))
                .add(35, 35, 35)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(maxNoHitStreakPlayer1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penNoHitStreakPlayer1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel33)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel29))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(maxHitStreakPlayer1)
                            .add(jLabel31))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel27)
                            .add(penHitStreakPlayer1))))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, medianNoHitStreakPlayer1)
                            .add(jLabel38))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel40)
                            .add(averageNoHitStreakPlayer1)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel39)
                            .add(medianHitStreakPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel41)
                            .add(averageHitStreakPlayer1))))
                .add(35, 35, 35)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel14)
                            .add(baPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel15)
                            .add(obpPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(onBaseConsistencyPlayer1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel46)
                            .add(hitConsistencyPlayer1)))
                    .add(errorReport1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(66, 66, 66)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(yearStartPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(lastNamePlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22)
                    .add(firstNamePlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel24)
                    .add(yearEndPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel36)
                            .add(maxNoBaseStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel34)
                            .add(penNoBaseStreakPlayer2)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel35)
                            .add(maxOnBaseStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel32)
                            .add(penOnBaseStreakPlayer2))))
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel19)
                            .add(medianOnBaseStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel21)
                            .add(averageOnBaseStreakPlayer2)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel20))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(medianNoBaseStreakPlayer2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(averageNoBaseStreakPlayer2)))
                .add(35, 35, 35)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel37)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel53))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(maxNoHitStreakPlayer2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penNoHitStreakPlayer2))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel52)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, maxHitStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel54)
                            .add(penHitStreakPlayer2))))
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel51)
                            .add(medianNoHitStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel49)
                            .add(averageNoHitStreakPlayer2)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel50)
                            .add(medianHitStreakPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel48)
                            .add(averageHitStreakPlayer2))))
                .add(35, 35, 35)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(baPlayer2)
                            .add(jLabel28))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel30)
                            .add(obpPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel26)
                            .add(onBaseConsistencyPlayer2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel47)
                            .add(hitConsistencyPlayer2)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, errorReport2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(80, 80, 80))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {averageHitStreakPlayer1, averageOnBaseStreakPlayer1, baPlayer1, hitConsistencyPlayer1, maxHitStreakPlayer1, maxOnBaseStreakPlayer1, medianHitStreakPlayer1, medianOnBaseStreakPlayer1, obpPlayer1, onBaseConsistencyPlayer1, penHitStreakPlayer1, penOnBaseStreakPlayer1}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageNoBaseStreakPlayer1, averageNoHitStreakPlayer1, maxNoBaseStreakPlayer1, maxNoHitStreakPlayer1, medianNoBaseStreakPlayer1, medianNoHitStreakPlayer1, penNoBaseStreakPlayer1, penNoHitStreakPlayer1}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageHitStreakPlayer2, averageOnBaseStreakPlayer2, baPlayer2, hitConsistencyPlayer2, maxHitStreakPlayer2, maxOnBaseStreakPlayer2, medianHitStreakPlayer2, medianOnBaseStreakPlayer2, obpPlayer2, onBaseConsistencyPlayer2, penHitStreakPlayer2, penOnBaseStreakPlayer2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {averageNoBaseStreakPlayer2, averageNoHitStreakPlayer2, maxNoBaseStreakPlayer2, maxNoHitStreakPlayer2, medianNoBaseStreakPlayer2, medianNoHitStreakPlayer2, penNoBaseStreakPlayer2, penNoHitStreakPlayer2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel18, jLabel20, jLabel34, jLabel36}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jScrollPane1.setViewportView(jPanel1);

        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(go)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(go)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        if ("".equals(firstNamePlayer1.getText().trim()) || "".equals(yearStartPlayer1.getText().trim()) || "".equals(lastNamePlayer1.getText().trim())) {
        } else {
            player1.Calculate(firstNamePlayer1.getText(), lastNamePlayer1.getText(), yearStartPlayer1.getText(), yearEndPlayer1.getText(), "");
            if (player1.error) {
                maxOnBaseStreakPlayer1.setText("");
                maxNoBaseStreakPlayer1.setText("");
                penOnBaseStreakPlayer1.setText("");
                penNoBaseStreakPlayer1.setText("");
                medianOnBaseStreakPlayer1.setText("");
                medianNoBaseStreakPlayer1.setText("");
                averageOnBaseStreakPlayer1.setText("");
                averageNoBaseStreakPlayer1.setText("");
                maxHitStreakPlayer1.setText("");
                maxNoHitStreakPlayer1.setText("");
                penHitStreakPlayer1.setText("");
                penNoHitStreakPlayer1.setText("");
                medianHitStreakPlayer1.setText("");
                medianNoHitStreakPlayer1.setText("");
                averageHitStreakPlayer1.setText("");
                averageNoHitStreakPlayer1.setText("");
                baPlayer1.setText("");
                obpPlayer1.setText("");
                onBaseConsistencyPlayer1.setText("");
                hitConsistencyPlayer1.setText("");
                errorReport1.setText("There has been an error with the file you requested.");
            } else {
                maxOnBaseStreakPlayer1.setText(Integer.toString(player1.onBaseStreakMedianArray[player1.onBaseStreakMedianArray.length - 1]));
                maxNoBaseStreakPlayer1.setText(Integer.toString(player1.noBaseStreakMedianArray[player1.noBaseStreakMedianArray.length - 1]));
                penOnBaseStreakPlayer1.setText(Integer.toString(player1.onBaseStreakMedianArray[player1.onBaseStreakMedianArray.length - player1.onBaseTopFivePercent]));
                penNoBaseStreakPlayer1.setText(Integer.toString(player1.noBaseStreakMedianArray[player1.noBaseStreakMedianArray.length - player1.noBaseTopFivePercent]));
                medianOnBaseStreakPlayer1.setText(Double.toString(player1.finalOnBaseStreakMedian));
                medianNoBaseStreakPlayer1.setText(Double.toString(player1.finalNoBaseStreakMedian));
                averageOnBaseStreakPlayer1.setText(Double.toString(player1.onBaseStreakAverage));
                averageNoBaseStreakPlayer1.setText(Double.toString(player1.noBaseStreakAverage));
                maxHitStreakPlayer1.setText(Integer.toString(player1.hitStreakMedianArray[player1.hitStreakMedianArray.length - 1]));
                maxNoHitStreakPlayer1.setText(Integer.toString(player1.noHitStreakMedianArray[player1.noHitStreakMedianArray.length - 1]));
                penHitStreakPlayer1.setText(Integer.toString(player1.hitStreakMedianArray[player1.hitStreakMedianArray.length - player1.hitTopFivePercent]));
                penNoHitStreakPlayer1.setText(Integer.toString(player1.noHitStreakMedianArray[player1.noHitStreakMedianArray.length - player1.noHitTopFivePercent]));
                medianHitStreakPlayer1.setText(Double.toString(player1.finalHitStreakMedian));
                medianNoHitStreakPlayer1.setText(Double.toString(player1.finalNoHitStreakMedian));
                averageHitStreakPlayer1.setText(Double.toString(player1.hitStreakAverage));
                averageNoHitStreakPlayer1.setText(Double.toString(player1.noHitStreakAverage));
                baPlayer1.setText(Double.toString(player1.ba));
                obpPlayer1.setText(Double.toString(player1.obp));
                onBaseConsistencyPlayer1.setText(Double.toString(player1.onBaseCI));
                hitConsistencyPlayer1.setText(Double.toString(player1.hitCI));
                errorReport1.setText("For entire career, enter \"Yr Start\" as 0.");
            }
        }

        if ("".equals(firstNamePlayer2.getText().trim()) || "".equals(yearStartPlayer2.getText().trim()) || "".equals(lastNamePlayer2.getText().trim())) {
        } else {
            player1.Calculate(firstNamePlayer2.getText(), lastNamePlayer2.getText(), yearStartPlayer2.getText(), yearEndPlayer2.getText(), "");
            if (player1.error) {
                maxOnBaseStreakPlayer2.setText("");
                maxNoBaseStreakPlayer2.setText("");
                penOnBaseStreakPlayer2.setText("");
                penNoBaseStreakPlayer2.setText("");
                medianOnBaseStreakPlayer2.setText("");
                medianNoBaseStreakPlayer2.setText("");
                averageOnBaseStreakPlayer2.setText("");
                averageNoBaseStreakPlayer2.setText("");
                maxHitStreakPlayer2.setText("");
                maxNoHitStreakPlayer2.setText("");
                penHitStreakPlayer2.setText("");
                penNoHitStreakPlayer2.setText("");
                medianHitStreakPlayer2.setText("");
                medianNoHitStreakPlayer2.setText("");
                averageHitStreakPlayer2.setText("");
                averageNoHitStreakPlayer2.setText("");
                baPlayer2.setText("");
                obpPlayer2.setText("");
                onBaseConsistencyPlayer2.setText("");
                hitConsistencyPlayer2.setText("");
                errorReport2.setText("There has been an error with the file you requested.");
            } else {
                maxOnBaseStreakPlayer2.setText(Integer.toString(player1.onBaseStreakMedianArray[player1.onBaseStreakMedianArray.length - 1]));
                maxNoBaseStreakPlayer2.setText(Integer.toString(player1.noBaseStreakMedianArray[player1.noBaseStreakMedianArray.length - 1]));
                penOnBaseStreakPlayer2.setText(Integer.toString(player1.onBaseStreakMedianArray[player1.onBaseStreakMedianArray.length - player1.onBaseTopFivePercent]));
                penNoBaseStreakPlayer2.setText(Integer.toString(player1.noBaseStreakMedianArray[player1.noBaseStreakMedianArray.length - player1.noBaseTopFivePercent]));
                medianOnBaseStreakPlayer2.setText(Double.toString(player1.finalOnBaseStreakMedian));
                medianNoBaseStreakPlayer2.setText(Double.toString(player1.finalNoBaseStreakMedian));
                averageOnBaseStreakPlayer2.setText(Double.toString(player1.onBaseStreakAverage));
                averageNoBaseStreakPlayer2.setText(Double.toString(player1.noBaseStreakAverage));
                maxHitStreakPlayer2.setText(Integer.toString(player1.hitStreakMedianArray[player1.hitStreakMedianArray.length - 1]));
                maxNoHitStreakPlayer2.setText(Integer.toString(player1.noHitStreakMedianArray[player1.noHitStreakMedianArray.length - 1]));
                penHitStreakPlayer2.setText(Integer.toString(player1.hitStreakMedianArray[player1.hitStreakMedianArray.length - player1.hitTopFivePercent]));
                penNoHitStreakPlayer2.setText(Integer.toString(player1.noHitStreakMedianArray[player1.noHitStreakMedianArray.length - player1.noHitTopFivePercent]));
                medianHitStreakPlayer2.setText(Double.toString(player1.finalHitStreakMedian));
                medianNoHitStreakPlayer2.setText(Double.toString(player1.finalNoHitStreakMedian));
                averageHitStreakPlayer2.setText(Double.toString(player1.hitStreakAverage));
                averageNoHitStreakPlayer2.setText(Double.toString(player1.noHitStreakAverage));
                baPlayer2.setText(Double.toString(player1.ba));
                obpPlayer2.setText(Double.toString(player1.obp));
                onBaseConsistencyPlayer2.setText(Double.toString(player1.onBaseCI));
                hitConsistencyPlayer2.setText(Double.toString(player1.hitCI));
                errorReport2.setText("To calculate up to latest year, leave Yr End blank.");
            }
        }
    }//GEN-LAST:event_goActionPerformed

    private void yearStartPlayer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearStartPlayer1FocusGained
        yearStartPlayer1.selectAll();
    }//GEN-LAST:event_yearStartPlayer1FocusGained

    private void yearStartPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearStartPlayer1ActionPerformed
        goActionPerformed(evt);
    }//GEN-LAST:event_yearStartPlayer1ActionPerformed

    private void firstNamePlayer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNamePlayer1FocusGained
        firstNamePlayer1.selectAll();
    }//GEN-LAST:event_firstNamePlayer1FocusGained

    private void lastNamePlayer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNamePlayer1FocusGained
        lastNamePlayer1.selectAll();
    }//GEN-LAST:event_lastNamePlayer1FocusGained

    private void firstNamePlayer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNamePlayer2FocusGained
        firstNamePlayer2.selectAll();
    }//GEN-LAST:event_firstNamePlayer2FocusGained

    private void lastNamePlayer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNamePlayer2FocusGained
        lastNamePlayer2.selectAll();
    }//GEN-LAST:event_lastNamePlayer2FocusGained

    private void yearStartPlayer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearStartPlayer2FocusGained
        yearStartPlayer2.selectAll();
    }//GEN-LAST:event_yearStartPlayer2FocusGained

    private void yearStartPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearStartPlayer2ActionPerformed
        goActionPerformed(evt);
    }//GEN-LAST:event_yearStartPlayer2ActionPerformed

    private void yearEndPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearEndPlayer1ActionPerformed
        goActionPerformed(evt);
    }//GEN-LAST:event_yearEndPlayer1ActionPerformed

    private void yearEndPlayer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearEndPlayer1FocusGained
        yearEndPlayer1.selectAll();
    }//GEN-LAST:event_yearEndPlayer1FocusGained

    private void yearEndPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearEndPlayer2ActionPerformed
        goActionPerformed(evt);
    }//GEN-LAST:event_yearEndPlayer2ActionPerformed

    private void yearEndPlayer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearEndPlayer2FocusGained
        yearEndPlayer2.selectAll();
    }//GEN-LAST:event_yearEndPlayer2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consistency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consistency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consistency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consistency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consistency().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageHitStreakPlayer1;
    private javax.swing.JLabel averageHitStreakPlayer2;
    private javax.swing.JLabel averageNoBaseStreakPlayer1;
    private javax.swing.JLabel averageNoBaseStreakPlayer2;
    private javax.swing.JLabel averageNoHitStreakPlayer1;
    private javax.swing.JLabel averageNoHitStreakPlayer2;
    private javax.swing.JLabel averageOnBaseStreakPlayer1;
    private javax.swing.JLabel averageOnBaseStreakPlayer2;
    private javax.swing.JLabel baPlayer1;
    private javax.swing.JLabel baPlayer2;
    private javax.swing.JLabel errorReport1;
    private javax.swing.JLabel errorReport2;
    private javax.swing.JTextField firstNamePlayer1;
    private javax.swing.JTextField firstNamePlayer2;
    private javax.swing.JButton go;
    private javax.swing.JLabel hitConsistencyPlayer1;
    private javax.swing.JLabel hitConsistencyPlayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNamePlayer1;
    private javax.swing.JTextField lastNamePlayer2;
    private javax.swing.JLabel maxHitStreakPlayer1;
    private javax.swing.JLabel maxHitStreakPlayer2;
    private javax.swing.JLabel maxNoBaseStreakPlayer1;
    private javax.swing.JLabel maxNoBaseStreakPlayer2;
    private javax.swing.JLabel maxNoHitStreakPlayer1;
    private javax.swing.JLabel maxNoHitStreakPlayer2;
    private javax.swing.JLabel maxOnBaseStreakPlayer1;
    private javax.swing.JLabel maxOnBaseStreakPlayer2;
    private javax.swing.JLabel medianHitStreakPlayer1;
    private javax.swing.JLabel medianHitStreakPlayer2;
    private javax.swing.JLabel medianNoBaseStreakPlayer1;
    private javax.swing.JLabel medianNoBaseStreakPlayer2;
    private javax.swing.JLabel medianNoHitStreakPlayer1;
    private javax.swing.JLabel medianNoHitStreakPlayer2;
    private javax.swing.JLabel medianOnBaseStreakPlayer1;
    private javax.swing.JLabel medianOnBaseStreakPlayer2;
    private javax.swing.JLabel obpPlayer1;
    private javax.swing.JLabel obpPlayer2;
    private javax.swing.JLabel onBaseConsistencyPlayer1;
    private javax.swing.JLabel onBaseConsistencyPlayer2;
    private javax.swing.JLabel penHitStreakPlayer1;
    private javax.swing.JLabel penHitStreakPlayer2;
    private javax.swing.JLabel penNoBaseStreakPlayer1;
    private javax.swing.JLabel penNoBaseStreakPlayer2;
    private javax.swing.JLabel penNoHitStreakPlayer1;
    private javax.swing.JLabel penNoHitStreakPlayer2;
    private javax.swing.JLabel penOnBaseStreakPlayer1;
    private javax.swing.JLabel penOnBaseStreakPlayer2;
    private javax.swing.JTextField yearEndPlayer1;
    private javax.swing.JTextField yearEndPlayer2;
    private javax.swing.JTextField yearStartPlayer1;
    private javax.swing.JTextField yearStartPlayer2;
    // End of variables declaration//GEN-END:variables
}
